# Generated by Django 5.2.1 on 2025-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playlist',
            name='members',
            field=models.ManyToManyField(related_name='playlists', to='song.member'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='playlist',
        ),
    ]
